global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tiny-url-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "tiny_url"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:9568"]
        labels:
          app: "tiny_url"
          env: "dev"
